apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking
data:
  EUREKA_URI: "http://eureka-server:8761/eureka/"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  DB_DRIVER: "org.postgresql.Driver"
  HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
