apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  DB_USERNAME: "banking"
  DB_PASSWORD: "banking123"
  JWT_SECRET: "mysecretkey123456789012345678901"
